version: "3.8"

services:
  gitlab-redis:
    restart: always
    image: redis:6.2.6
    command:
      - --loglevel warning
    volumes:
      - redis-data-volume:/data

  gitlab-postgresql:
    restart: always
    image: postgres:14-alpine
    volumes:
      - postgresql-volume:/var/lib/postgresql:Z
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  gitlab-runner:
    image: "gitlab/gitlab-runner:latest"
    depends_on:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner-config:/etc/gitlab-runner
    restart: unless-stopped

  gitlab:
    restart: always
    image: sameersbn/gitlab:14.9.3
    depends_on:
      - gitlab-redis
      - gitlab-postgresql
    ports:
      - "${GITLAB_PORT}:80"
      - "${GITLAB_SSH_PORT}:22"
    volumes:
      - gitlab-data-volume:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    environment:
      - DEBUG=false
      - DB_ADAPTER=postgresql
      - DB_HOST=gitlab-postgresql
      - DB_PORT=5432
      - GITLAB_HTTPS=false
      - SSL_SELF_SIGNED=false
      - REDIS_HOST=gitlab-redis
      - REDIS_PORT=6379
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}

      - TZ=${GITLAB_TIMEZONE}
      - GITLAB_TIMEZONE=${GITLAB_TIMEZONE}

      - GITLAB_HOST=${GITLAB_HOST}
      - GITLAB_PORT=${GITLAB_PORT}
      - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
      - GITLAB_RELATIVE_URL_ROOT=
      - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE}
      - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE}
      - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE}

      - "OAUTH_SAML_ASSERTION_CONSUMER_SERVICE_URL=http://${GITLAB_HOST}:${GITLAB_PORT}/users/auth/saml/callback"
      - "OAUTH_SAML_IDP_CERT_FINGERPRINT=${OAUTH_SAML_IDP_CERT_FINGERPRINT}"
      - "OAUTH_SAML_IDP_SSO_TARGET_URL=${OAUTH_SAML_IDP_SSO_TARGET_URL}"
      - "OAUTH_SAML_ISSUER=${OAUTH_SAML_ISSUER}"
      - "OAUTH_SAML_NAME_IDENTIFIER_FORMAT=${OAUTH_SAML_NAME_IDENTIFIER_FORMAT}"
      # - GITLAB_ROOT_PASSWORD=
      # - GITLAB_ROOT_EMAIL=

      # - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      # - GITLAB_NOTIFY_PUSHER=false

      # - GITLAB_EMAIL=notifications@example.com
      # - GITLAB_EMAIL_REPLY_TO=noreply@example.com
      # - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      # - GITLAB_BACKUP_SCHEDULE=daily
      # - GITLAB_BACKUP_TIME=01:00

      # - SMTP_ENABLED=false
      # - SMTP_DOMAIN=www.example.com
      # - SMTP_HOST=smtp.gmail.com
      # - SMTP_PORT=587
      # - SMTP_USER=mailer@example.com
      # - SMTP_PASS=password
      # - SMTP_STARTTLS=true
      # - SMTP_AUTHENTICATION=login

      # - IMAP_ENABLED=false
      # - IMAP_HOST=imap.gmail.com
      # - IMAP_PORT=993
      # - IMAP_USER=mailer@example.com
      # - IMAP_PASS=password
      # - IMAP_SSL=true
      # - IMAP_STARTTLS=false

      # - OAUTH_ENABLED=false
      # - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=
      # - OAUTH_ALLOW_SSO=
      # - OAUTH_BLOCK_AUTO_CREATED_USERS=true
      # - OAUTH_AUTO_LINK_LDAP_USER=false
      # - OAUTH_AUTO_LINK_SAML_USER=false
      # - OAUTH_EXTERNAL_PROVIDERS=

      # - OAUTH_CAS3_LABEL=cas3
      # - OAUTH_CAS3_SERVER=
      # - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=false
      # - OAUTH_CAS3_LOGIN_URL=/cas/login
      # - OAUTH_CAS3_VALIDATE_URL=/cas/p3/serviceValidate
      # - OAUTH_CAS3_LOGOUT_URL=/cas/logout

      # - OAUTH_GOOGLE_API_KEY=
      # - OAUTH_GOOGLE_APP_SECRET=
      # - OAUTH_GOOGLE_RESTRICT_DOMAIN=

      # - OAUTH_FACEBOOK_API_KEY=
      # - OAUTH_FACEBOOK_APP_SECRET=

      # - OAUTH_TWITTER_API_KEY=
      # - OAUTH_TWITTER_APP_SECRET=

      # - OAUTH_GITHUB_API_KEY=
      # - OAUTH_GITHUB_APP_SECRET=
      # - OAUTH_GITHUB_URL=
      # - OAUTH_GITHUB_VERIFY_SSL=

      # - OAUTH_GITLAB_API_KEY=
      # - OAUTH_GITLAB_APP_SECRET=

      # - OAUTH_BITBUCKET_API_KEY=
      # - OAUTH_BITBUCKET_APP_SECRET=
      # - OAUTH_BITBUCKET_URL=

      # - OAUTH_SAML_GROUPS_ATTRIBUTE=
      # - OAUTH_SAML_EXTERNAL_GROUPS=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_EMAIL=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_NAME=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_USERNAME=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_FIRST_NAME=
      # - OAUTH_SAML_ATTRIBUTE_STATEMENTS_LAST_NAME=

      # - OAUTH_CROWD_SERVER_URL=
      # - OAUTH_CROWD_APP_NAME=
      # - OAUTH_CROWD_APP_PASSWORD=

      # - OAUTH_AUTH0_CLIENT_ID=
      # - OAUTH_AUTH0_CLIENT_SECRET=
      # - OAUTH_AUTH0_DOMAIN=
      # - OAUTH_AUTH0_SCOPE=

      # - OAUTH_AZURE_API_KEY=
      # - OAUTH_AZURE_API_SECRET=
      # - OAUTH_AZURE_TENANT_ID=

volumes:
  redis-data-volume:
  postgresql-volume:
    driver: local
  gitlab-data-volume:
    driver: local
